routes/web.php
<?php

use App\Http\Controllers\Auth\SocialLoginController;
use App\Http\Controllers\Backend\ArticleController;
use App\Http\Controllers\Backend\AssignPermissionController;
use App\Http\Controllers\Backend\AssignRoleController;
use App\Http\Controllers\Backend\BankEwalletController;
use App\Http\Controllers\Backend\DashboardController;
use App\Http\Controllers\Backend\LogController;
use App\Http\Controllers\Backend\PermissionController;
use App\Http\Controllers\Backend\RoleController;
use App\Http\Controllers\Backend\UserController;
use App\Http\Controllers\Backend\CategorieController;
use App\Http\Controllers\Backend\CategorieProductController;
use App\Http\Controllers\Backend\CommentController as BackendCommentController;
use App\Http\Controllers\Backend\OrderController as BackendOrderController;
use App\Http\Controllers\Backend\ProductController;
use App\Http\Controllers\Frontend\BlogController;
use App\Http\Controllers\Frontend\CartController;
use App\Http\Controllers\Frontend\CheckoutController;
use App\Http\Controllers\Frontend\CommentController;
use App\Http\Controllers\Frontend\CommentReplyController;
use App\Http\Controllers\Frontend\FrontendController;
use App\Http\Controllers\Frontend\OrderController;
use App\Http\Controllers\Frontend\ProfileController;
use App\Http\Controllers\Frontend\ProfileUserController;
use App\Http\Controllers\Frontend\RatingController;
use App\Http\Controllers\Frontend\ReviewController;
use App\Http\Controllers\Frontend\WishlistController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;


// LOGIN DENGAN GOOGLE
Route::get('login/google', [SocialLoginController::class, 'redirectGoogle'])->name('login.google');
Route::get('login/google/callback', [SocialLoginController::class, 'callbackGoogle'])->name('google.callback');

// LOGIN DENGAN FACEBOOK
Route::get('login/facebook', [SocialLoginController::class, 'redirectFacebook'])->name('login.facebook');
Route::get('login/facebook/callback', [SocialLoginController::class, 'callbackFacebook'])->name('facebook.callback');


// LOGIN DENGAN GITHUB
Route::get('login/github', [SocialLoginController::class, 'redirectGithub'])->name('login.github');
Route::get('login/github/callback', [SocialLoginController::class, 'callbackGithub'])->name('github.callback');




// HALAMAN FRONTEND HOME
Route::get('/', [FrontendController::class, 'index'])->name('user.index');

// HALAMAN FRONTEND STORE
Route::get('store', [FrontendController::class, 'store'])->name('store.index');
Route::get('product-list', [FrontendController::class, 'search']);
Route::post('searchproduct', [FrontendController::class, 'searchproduct'])->name('searchproduct');
Route::get('categorie-product/{slug}', [FrontendController::class, 'viewcategorie'])->name('viewcategorie.index');
Route::get('categorie-product/{cate_slug}/{prod_slug}', [FrontendController::class, 'productview'])->name('productview.index');

// HALAMAN FRONTEND BLOG
Route::get('blog', [BlogController::class, 'index'])->name('blog.index');
Route::get('blog/categorie/{slug}', [BlogController::class, 'categorie'])->name('blog.categorie');
Route::get('/blog/detail/{slug}', [BlogController::class, 'detail'])->name('detail');
Route::get('/blog/author/{username}', [BlogController::class, 'author'])->name('author');
Route::get('artikel-list', [BlogController::class, 'search']);
Route::post('searchartikel', [BlogController::class, 'searchartikel'])->name('searchartikel');
Route::post('/comment-artikel/{artikel}', [CommentController::class, 'store'])->name('commentartikel.store');
Route::post('/comment-reply/{comment}', [CommentReplyController::class, 'store'])->name('commentreply.store');
Route::post('/like-post/{artikel}', [BlogController::class, 'likeArticle'])->name('artikel.like');

// ADD TO CART
Route::post('add-to-cart', [CartController::class, 'addProduct'])->name('addcart');

// ADD TO WISHLITS
Route::post('add-to-wishlist', [WishlistController::class, 'add'])->name('addwishlist');

// REMOVE CART LIST
Route::post('delete-cart-item', [CartController::class, 'deleteproduct']);

// REMOVE WISH LIST
Route::post('delete-wishlist-item', [WishlistController::class, 'deletewishlist']);

// UPDATE CART
Route::post('update-cart', [CartController::class, 'updatecart']);

// CART COUNT
Route::get('/load-cart-data',[CartController::class, 'cartcount']);

// WISHLIST COUNT
Route::get('/load-wishlist-data', [WishlistController::class, 'wishlistcount']);


Route::middleware(['has.role'])->middleware('auth')->group(function (){
    // ROUTE CATEGORIE PRODUCT
    Route::resource('categorieproduct', CategorieProductController::class);

    // ROUTE PRODUCT
    Route::resource('product', ProductController::class);

    // ROUTE CART LIST
    Route::get('cart', [CartController::class, 'cartview'])->name('cartview.index');

    // ROUTE WISHLIST
    Route::get('wishlist', [WishlistController::class, 'index'])->name('wishlist.index');

    // ROUTE CHECKOUT
    Route::get('checkout', [CheckoutController::class, 'index'])->name('checkout.index');

    // ROUTE PLACE ORDER
    Route::post('place-order', [CheckoutController::class, 'placeorder']);

    // ROUTE MIDTRANS
    Route::get('place-order-midtrans', [CheckoutController::class, 'midtrans']);

    // ROUTE CEK ORDER
    Route::get('my-orders', [OrderController::class, 'index'])->name('myorder.index');

    // ROUTE VIEW ORDER
    Route::get('view-orders/{id}', [OrderController::class, 'view'])->name('vieworders');

    // ROUTE ADD RATING
    Route::post('add-rating', [RatingController::class, 'add'])->name('rating');

    // ROUTE REVIEW PRODUCT
    Route::get('add-review/{product_slug}/userreview', [ReviewController::class, 'add'])->name('review');

    // ROUTE POST REVIEW PRODUCT
    Route::post('add-review', [ReviewController::class, 'create']);

    // ROUTE EDIT REVIEW PRODUCT
    Route::get('review-edit/{product_slug}/userreview', [ReviewController::class, 'edit']);

    // ROUTE UPDATE REVIEW PRODUCT
    Route::put('update-review', [ReviewController::class, 'update']);
});


Auth::routes();


Route::middleware(['has.role'])->middleware('auth')->group(function (){
    // DASHBOARD
    Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');

    // ROUTE FOR ARTICLE
    Route::resource('article', ArticleController::class);
    Route::resource('categorie', CategorieController::class);
    Route::resource('comment', BackendCommentController::class);

    // ROUTE ADMIN ORDER
    Route::resource('orders', BackendOrderController::class);
    Route::get('orders-completed', [BackendOrderController::class, 'completed'])->name('completed.index');

    // ROLE USER
    Route::get('role/trash', [RoleController::class, 'trash'])->name('role.trash');
    Route::get('role/restore/{id?}', [RoleController::class, 'restore'])->name('role.restore');
    Route::get('role/delete/{id?}', [RoleController::class, 'delete'])->name('role.delete');
    Route::resource('role', RoleController::class);

    // ROLE PERMISSION
    Route::get('permission/trash', [PermissionController::class, 'trash'])->name('permission.trash');
    Route::get('permission/restore/{id?}', [PermissionController::class, 'restore'])->name('permission.restore');
    Route::get('permission/delete/{id?}', [PermissionController::class, 'delete'])->name('permission.delete');
    Route::resource('permission', PermissionController::class);

    // ASSIGN PERMISSION TO ROLE
    Route::get('assignpermission', [AssignPermissionController::class, 'index'])->name('assignpermission.index');
    Route::post('assignpermission', [AssignPermissionController::class, 'store'])->name('assignpermission.index');
    Route::get('assignpermission/{role}/edit', [AssignPermissionController::class, 'edit'])->name('assignpermission.edit');
    Route::put('assignpermission/{role}/edit', [AssignPermissionController::class, 'update']);

    // ASSIGN ROLE TO USER
    Route::get('assignrole', [AssignRoleController::class, 'index'])->name('assignrole.index');
    Route::post('assignrole', [AssignRoleController::class, 'store'])->name('assignrole.index');
    Route::get('assignrole/{user}/edit', [AssignRoleController::class, 'edit'])->name('assignrole.edit');
    Route::put('assignrole/{user}/edit', [AssignRoleController::class, 'update']);

    // MANAJEMEN USER
    Route::get('editpassword/{user}/edit', [UserController::class, 'editpassword'])->name('editpassword');
    Route::put('editpassword/{user}/edit', [UserController::class, 'updatepassword'])->name('updatepassword');
    Route::get('users/trash', [UserController::class, 'trash'])->name('users.trash');
    Route::get('users/restore/{id?}', [UserController::class, 'restore'])->name('users.restore');
    Route::get('users/delete/{id?}', [UserController::class, 'delete'])->name('users.delete');
    Route::resource('users', UserController::class);

    // SETTING PROFILE
    Route::get('profile', [ProfileController::class, 'index'])->name('profile.index');
    Route::put('profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::get('setting-profile', [ProfileUserController::class, 'index'])->name('userprofile.index');
    Route::put('setting-profile', [ProfileUserController::class, 'update'])->name('userprofile.update');

    // SETTING BANK & EWALLET
    // Route::get('setting-payment', [BankEwalletController::class, 'index'])->name('payment.index');
    // Route::get('create-payment', [BankEwalletController::class, 'create'])->name('payment.cretae');
    // Route::post('store-payment', [BankEwalletController::class, 'store'])->name('payment.store');
    // Route::get('edit-payment/{id}/edit', [BankEwalletController::class, 'edit'])->name('payment.edit');
    // Route::put('update-payment/{id}', [BankEwalletController::class, 'update'])->name('payment.update');
    // Route::get('delete-payment/{id}', [BankEwalletController::class, 'destroy'])->name('payment.delete');

app/Models/Article.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    use HasFactory;

    protected $table = 'articles';

    protected $fillable = ['judul', 'slug', 'deskripsi', 'kategori_id', 'user_id', 'gambar_artikel', 'is_active', 'tgl_publish'];

    protected $hidden = [];

    public function categories()
    {
        return $this->belongsTo(Categorie::class, 'kategori_id', 'id');
    }

    public function users()
    {
        return $this->belongsTo(User::class, 'user_id', 'id');
    }

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    public function likedUsers()
    {
        return $this->belongsToMany(User::class)->withTimestamps();
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }
}

app/Http/Controllers/Backend/ArticleController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Article;
use App\Models\Categorie;
use App\Models\Tag;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;

class ArticleController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }


    public function index()
    {
        $articles = Article::orderBy('created_at','desc')->get();

        return view('admin.article.index', compact('articles'));
    }


    public function create()
    {
        $articles = Article::all();
        $categories = Categorie::all();

        return view('admin.article.create', compact('articles', 'categories'));
    }


    public function store(Request $request)
    {
        request()->validate([
            'judul' => 'required|string|unique:articles,judul',
            'gambar_artikel' => 'image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            'deskripsi' => 'required',
            'kategori_id' => 'required',
        ]);


        if (empty($request->file('gambar_artikel'))) {
            Article::create([
                'judul' => $request->judul,
                'slug' => Str::slug($request->judul),
                'deskripsi' => $request->deskripsi,
                'kategori_id' => $request->kategori_id,
                'is_active' => $request->is_active,
                'tgl_publish' => $request->tgl_publish ?? (now()),
                'user_id' => Auth::id(),
                'gambar_artikel' => $request->gambar_artikel ?? '',
            ]);

            toast('Data Berhasil Ditambahkan','success');

            return redirect()->route('article.index');

        } else {

            Article::create([
                'judul' => $request->judul,
                'slug' => Str::slug($request->judul),
                'deskripsi' => $request->deskripsi,
                'kategori_id' => $request->kategori_id,
                'is_active' => $request->is_active,
                'tgl_publish' => $request->tgl_publish ?? (now()),
                'user_id' => Auth::id(),
                'gambar_artikel' => $request->file('gambar_artikel')->store('gambar-artikel'),
            ]);

            toast('Data Berhasil Ditambahkan','success');

            return redirect()->route('article.index');
        }
    }


    public function edit($id)
    {
        $articles = Article::findOrFail($id);
        $categories = Categorie::all();


        return view('admin.article.edit', compact('articles', 'categories'));
    }


    public function show($id)
    {
        return view('admin.article.show', [
            'articles' => Article::findOrFail($id)
        ]);
    }


    public function update(Request $request, $id)
    {
        request()->validate([
            'judul' => 'required|string|unique:articles,judul,'.$id,
            'gambar_artikel' => 'image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            'deskripsi' => 'required',
            'kategori_id' => 'required',
        ]);


        if (empty($request->file('gambar_artikel'))) {
            $articles = Article::find($id);
            $articles->update([
                'judul' => $request->judul,
                'slug' => Str::slug($request->judul),
                'deskripsi' => $request->deskripsi,
                'kategori_id' => $request->kategori_id,
                'tgl_publish' => $request->tgl_publish ?? (now()),
                'is_active' => $request->is_active,
                'user_id' => Auth::id(),
            ]);

            toast('Data Berhasil Diupdate','success');

            return redirect()->route('article.index');

        } else {
            $articles = Article::find($id);
            Storage::delete($articles->gambar_artikel);
            $articles->update([
                'judul' => $request->judul,
                'slug' => Str::slug($request->judul),
                'deskripsi' => $request->deskripsi,
                'kategori_id' => $request->kategori_id,
                'tgl_publish' => $request->tgl_publish ?? (now()),
                'is_active' => $request->is_active,
                'user_id' => Auth::id(),
                'gambar_artikel' => $request->file('gambar_artikel')->store('gambar-artikel'),
            ]);

            toast('Data Berhasil Diupdate','success');

            return redirect()->route('article.index');
        }
    }
}

resources/views/admin/article/create.blade.php
@extends('layouts-admin.layaouts', ['menu' => 'article', 'submenu' => 'post'])

@section('title', 'Create Article')

@section('content')

<div class="page-content">
    <!-- // Basic multiple Column Form section start -->
    <section id="multiple-column-form">
        <div class="row match-height">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Create Article</h4>
                        <a href="{{ route('article.index') }}" class="btn btn-sm text-primary" style="float: right"><i class="fas fa-backward"></i><a>
                        </div>
                        <div class="card-content">
                            <div class="card-body">

                                <form action="{{ route('article.store') }}" method="POST" enctype="multipart/form-data">
                                    @csrf
                                    <div class="row">
                                        <div class="">
                                            <div class="form-group">
                                                <label for="first-name-column">Judul</label>
                                                <div class="input-group mb-3">
                                                    <span class="input-group-text"><i class="bi bi-list-task"></i></span>
                                                    <input type="text" id="judul" name="judul" class="form-control  @error('judul') is-invalid @enderror"
                                                    placeholder="Juduk Article" value="{{ old('judul' ) }}" required autocomplete="judul">
                                                    @error('judul')
                                                    <span class="invalid-feedback" role="alert">
                                                        <strong>{{ $message }}</strong>
                                                    </span>
                                                    @enderror
                                                </div>
                                            </div>
                                        </div>
                                        <div class="mt-4">
                                            <div class="form-group">
                                                <h6>Categorie Article</h6>
                                                <fieldset class="form-group">
                                                    <select class="form-select" name="kategori_id" id="kategori_id" required>
                                                        <option disabled selected>--pilih kategori--</option>
                                                        @foreach ($categories as $item)
                                                        @if (old('kategori_id') == $item->id )
                                                        <option value="{{ $item->id }}" selected>{{ $item->nama_kategori }}</option>
                                                        @else
                                                        <option value="{{ $item->id }}">{{ $item->nama_kategori }}</option>
                                                        @endif
                                                        @endforeach
                                                    </select>
                                                    @error('kategori_id')
                                                    <div class="text-danger" mt-2 d-block>{{ $message }}</div>
                                                    @enderror
                                                </fieldset>
                                            </div>
                                        </div>
                                        <div class="mt-4">
                                            <div class="form-group">
                                                <label for="email-id-column">Gambar Artcile</label>
                                                <input class="form-control" id="gambar_artikel" name="gambar_artikel" type="file" autocomplete="gambar_artikel">
                                                @error('gambar_artikel')
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $message }}</strong>
                                                </span>
                                                @enderror
                                            </div>
                                        </div>
                                        <div class="mt-4">
                                            <div class="form-group">
                                                <h6>Status Article</h6>
                                                <fieldset class="form-group">
                                                    <select class="form-select" name="is_active" id="is_active" required>
                                                        <option disabled selected>--pilih status--</option>
                                                        <option value="1">Publish</option>
                                                        <option value="0">Draft</option>
                                                    </select>
                                                    @error('is_active')
                                                    <div class="text-danger" mt-2 d-block>{{ $message }}</div>
                                                    @enderror
                                                </fieldset>
                                            </div>
                                        </div>
                                        <div class="mt-4">
                                            <div class="form-group">
                                                <h6>Tanggal Publish</h6>
                                                <div class="input-group mb-3">
                                                    <span class="input-group-text"><i class="bi bi-calendar"></i></span>
                                                    <input type="date" id="tgl_publish" name="tgl_publish" class="form-control  @error('tgl_publish') is-invalid @enderror"
                                                    placeholder="Tgl Publish" value="{{ old('tgl_publish' ) }}" autocomplete="tgl_publish">
                                                    @error('tgl_publish')
                                                    <span class="invalid-feedback" role="alert">
                                                        <strong>{{ $message }}</strong>
                                                    </span>
                                                    @enderror
                                                </div>
                                            </div>
                                        </div>

                                        <div class="mt-4">
                                            <div class="form-group">
                                                <label for="email-id-column">Deskripsi</label>
                                                <textarea id="summernote" class="form-control" name="deskripsi" required autocomplete="deskripsi">{{ old('deskripsi') }}</textarea>
                                            </div>
                                        </div>
                                        <div class="col-12 d-flex justify-content-end">
                                            <button type="submit" class="btn btn-primary me-1 mb-1">Submit</button>
                                            <button type="reset" class="btn btn-danger me-1 mb-1">Reset</button>
                                        </div>
                                    </div>
                                </form>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- // Basic multiple Column Form section end -->
    </div>

    @endsection

resources/views/admin/article/index.blade.php
@extends('layouts-admin.layaouts', ['menu' => 'article', 'submenu' => 'post'])

@section('title', 'Article')

@section('content')

<section class="section">
    <div class="card">
        <div class="card-header">
            Table Article
            @can('roles.trash')
                <a href="{{ route('role.trash') }}" class="btn btn-sm text-primary" style="float: right"><i class="fas fa-table"></i> Data Terhapus<a>
            @endcan

            @can('roles.trash')
                <a href="{{ route('article.create') }}" class="btn btn-sm text-success" style="float: right"><i class="fas fa-plus"></i><a>
            @endcan
            </div>
            <div class="card-body">

                <table class="table table-striped" id="table1">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Judul</th>
                            <th>Author</th>
                            <th>Kategori</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($articles as $no => $item)
                        <tr>
                            <td>
                                @if ($item->gambar_artikel)
                                <div class="avatar avatar-md">
                                    <img src="{{ asset('storage/'. $item->gambar_artikel ) }}" alt="{{ $item->categories->nama_kategori }}">
                                </div>
                                @else
                                <div class="avatar avatar-md">
                                    <img src="{{ asset('template') }}/images/faces/profile.jpg" alt="{{ $item->categories->nama_kategori }}">
                                </div>
                                @endif
                            </td>
                            <td>{{ $item->judul }}</td>
                            <td>{{ $item->users->name }}</td>
                            <td>{{ $item->categories->nama_kategori }}</td>
                            <td>
                                @if ($item->is_active == '1')
                                Publish
                                @else
                                Draft
                                @endif
                            </td>
                            <td>
                                <a href="{{ route('article.show', $item->id ) }}" class="btn btn-sm text-info"><i class="fas fa-eye"></i></a>

                                <a href="{{ route('article.edit', $item->id ) }}" class="btn btn-sm text-primary"><i class="fas fa-edit"></i></a>

                                <form action="{{ route('article.destroy', $item->id ) }}" onsubmit="return confirm('Yakin anda akan menghapus article {{ $item->judul }}?')" method="POST" class="d-inline">
                                    @csrf
                                    @method('delete')
                                    <button class="btn btn-sm text-danger"><i class="fas fa-trash-alt"></i></button>
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </section>
</div>

@endsection

resources/views/admin/article/show.blade.php
@extends('layouts-admin.layaouts', ['menu' => 'article', 'submenu' => 'post'])

@section('title', 'Show Article')

@section('content')

<section class="section">
    <div class="card">
        <div class="card-header">
            Show Article
            @can('roles.trash')
                <a href="{{ route('article.index') }}" class="btn btn-sm text-primary" style="float: right"><i class="fas fa-backward"></i><a>
            @endcan

            </div>
            <div class="card-body">
                <div>
                <h2>{{ $articles->judul }}</h2><strong>{{ $articles->categories->nama_kategori }}</strong> By.<strong>{{ $articles->users->name }}</strong>
                </div>
                <div>
                    @if ($articles->gambar_artikel)
                        <img src="{{ asset('storage/'. $articles->gambar_artikel ) }}" style="height: 30%", width="30%" alt="Face 1">
                    @else
                        <img src="{{ asset('template') }}/images/faces/profile.jpg" style="height: 30%", width="30%" alt="Face 1">
                    @endif
                </div>
                <div class="mt-4">
                    {!! $articles->deskripsi !!}
                </div>
            </div>
        </div>
    </section>
</div>

@endsection